## Orthogonal Matrix Exercise (Topic 25)

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

(**Identity Matrix are orthogonal [$v \times w = 0$]**)

- Given Identity Matrix ($I_{3}$):

$$
\begin{bmatrix}
1 & 0 & 0 \\\\
0 & 1 & 0 \\\\
0 & 0 & 1
\end{bmatrix}
$$

1. With paper and pencil, use the dot product to demonstrate that any 2 columns of this $I_{3}$ matrix are orthogoa=nal to each other. (Code)

In [17]:
import numpy as np

i = np.array([[1,0,0], [0,1,0], [0,0,1]])

for idx in range(len(i)-1):
    orthogonal: bool = True if (np.dot((i[idx]), (i[idx+1])) == 0) else False
    print(orthogonal)

True
True


In [3]:
import numpy as np

i = np.array([[1,0,0], [0,1,0], [0,0,1]])

for idx in i:
    print(idx)
    for _ in idx:
        print('True' if (np.dot(idx, idx+1)) == 0 else 'False')

[1 0 0]
False
False
False
[0 1 0]
False
False
False
[0 0 1]
False
False
False


**Dot Product** is calculate by ($v_{1}w_{1} + v_{2} w_{1} + v_{n}w_{n}$), as the example we have 3 columns from the given identity matrix:

1. $[1, 0, 0]$,
2. $[0, 1, 0]$,
3. $[0, 0, 1]$

The dot product of the first and second columns will be like this:

$$
\begin{bmatrix}
1 \\\\
0 \\\\
0
\end{bmatrix}
\times
\begin{bmatrix}
0 \\\\
1 \\\\
0
\end{bmatrix}
=
\begin{bmatrix}
1 \times 0 \\\\
0 \times 1 \\\\
0 \times 0
\end{bmatrix}
=
\begin{bmatrix}
0 + 0 + 0
\end{bmatrix}
= 0
$$
Result of the dot product must be scalar else if become:
$[0, 0, 0]$ or
$$
\begin{bmatrix}
0 \\\\
0 \\\\
0
\end{bmatrix}
$$
It will be hadamard product (element-wise product)

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

2. Similarly, use paper and pencil to demonstrate that each of the coulmns $I_{3}$ has unit norm. (length (euclidean norm) = 1)

In [1]:
import numpy as np
import math

i1 = np.array([1,0,0])
i2 = np.array([0,1,0])
i3 = np.array([0,0,1])
sum1, sum2, sum3 = 0,0,0

# unit norm which is when Euclidean norm = 1
for _ in (i1):
    sum1 += _**2
    
for _ in (i2):
    sum2 += _**2
    
for _ in (i3):
    sum3 += _**2

print('All columns are unit norm.' if (sum1, sum2, sum3 == 1) else 'Not all columns are unit norm or neither any are unit norm.')

All columns are unit norm.


Unit norm is **A unit norm means that the length (magnitude, ความยาว) of a vector is exactly 1.** If we have a vector 

$$\begin{bmatrix} v_1 \\\\ v_2  \\\\ ... \\\\ v_n \end{bmatrix}$$

The euclidean norm (or exactly is $L^2$ Norm) is:

$$L^2 = \sqrt(v^2_1 + v^2_2 + ... v^2_n)$$

If it's equal to 1 then its unit norm.

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

3. Now using matrix $K$ instead of $I_3$,, repeat the exercises to assess whether $K$ is orthogonal.

Orthogonal Properties review:
- Each column has unit norm.
- The dot product between different columns is zero.

Matrix $K$:
$$
\begin{bmatrix}
\frac{2}{3} & \frac{1}{3} & \frac{2}{3} \\\\
\frac{-2}{3} & \frac{2}{3} & \frac{1}{3} \\\\
\frac{1}{3} & \frac{2}{3} & \frac{2}{3}
\end{bmatrix}
$$

In [15]:
import numpy as np

K: int = np.array([[2/3, 1/3, 2/3], [-2/3, 2/3, 1/3], [1/3, 2/3, 2/3]])


# check if dot product for each different
# columns are equal to 1
for i in range(K.shape[1]): # rows
    for j in range(K.shape[1]): # columns
        dot = np.dot(K[:, i], K[:, j])
        print(f"dot(col {i}, col {j}) =", dot)
        
# check if each column is unit norm
for idx in K:
    for element in idx:
        is_unit: bool = True if (math.sqrt(element**2 + (element+1)**2 + (element+2)**2)) else False
    print(f'Index: {idx}, Is all columns unit norm: {is_unit}')
    
print('This matrix is not orthogonal. Only unit norm is satisfied.')

dot(col 0, col 0) = 1.0
dot(col 0, col 1) = 0.0
dot(col 0, col 2) = 0.4444444444444444
dot(col 1, col 0) = 0.0
dot(col 1, col 1) = 1.0
dot(col 1, col 2) = 0.8888888888888888
dot(col 2, col 0) = 0.4444444444444444
dot(col 2, col 1) = 0.8888888888888888
dot(col 2, col 2) = 1.0
Index: [0.66666667 0.33333333 0.66666667], Is all columns unit norm: True
Index: [-0.66666667  0.66666667  0.33333333], Is all columns unit norm: True
Index: [0.33333333 0.66666667 0.66666667], Is all columns unit norm: True
This matrix is not orthogonal. Only unit norm is satisfied.
