## Orthogonal Matrix Exercise (Topic 25)

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

(**Identity Matrix are orthogonal [$v \times w = 0$]**)

- Given Identity Matrix ($I_{3}$):

$$
\begin{bmatrix}
1 & 0 & 0 \\\\
0 & 1 & 0 \\\\
0 & 0 & 1
\end{bmatrix}
$$

1. With paper and pencil, use the dot product to demonstrate that any 2 columns of this $I_{3}$ matrix are orthogoa=nal to each other. (Code)

In [17]:
import numpy as np

i = np.array([[1,0,0], [0,1,0], [0,0,1]])

for idx in range(len(i)-1):
    orthogonal: bool = True if (np.dot((i[idx]), (i[idx+1])) == 0) else False
    print(orthogonal)

True
True


In [3]:
import numpy as np

i = np.array([[1,0,0], [0,1,0], [0,0,1]])

for _ in range(len(i)):
    print(i[_])

[1 0 0]
[0 1 0]
[0 0 1]


**Dot Product** is calculate by ($v_{1}w_{1} + v_{2} w_{1} + v_{n}w_{n}$), as the example we have 3 columns from the given identity matrix:

1. $[1, 0, 0]$,
2. $[0, 1, 0]$,
3. $[0, 0, 1]$

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------